// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBolpZvFMsGia_9EkmEs00drPK06rwM6Xc',
    appId: '1:368127278359:web:991668fd370d3a66168b52',
    messagingSenderId: '368127278359',
    projectId: 'roadcam-abe6e',
    authDomain: 'roadcam-abe6e.firebaseapp.com',
    storageBucket: 'roadcam-abe6e.appspot.com',
    measurementId: 'G-4FBV15V3MW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUatVIyQQEZC2ZLICTTi6KPpFGRlfohco',
    appId: '1:368127278359:android:91b4c27ffa9cf0ae168b52',
    messagingSenderId: '368127278359',
    projectId: 'roadcam-abe6e',
    storageBucket: 'roadcam-abe6e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRtDyws8CWiujgY1RASGoSHafj2aKGXik',
    appId: '1:368127278359:ios:011178787a57bf68168b52',
    messagingSenderId: '368127278359',
    projectId: 'roadcam-abe6e',
    storageBucket: 'roadcam-abe6e.appspot.com',
    iosClientId:
        '368127278359-4jgs0o0mv994g65ome73akrcc31o654p.apps.googleusercontent.com',
    iosBundleId: 'com.example.drivesafe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRtDyws8CWiujgY1RASGoSHafj2aKGXik',
    appId: '1:368127278359:ios:011178787a57bf68168b52',
    messagingSenderId: '368127278359',
    projectId: 'roadcam-abe6e',
    storageBucket: 'roadcam-abe6e.appspot.com',
    iosClientId:
        '368127278359-4jgs0o0mv994g65ome73akrcc31o654p.apps.googleusercontent.com',
    iosBundleId: 'com.example.drivesafe',
  );
}
